sudo: required
services:
  - docker

# before_install:
  # - docker build -t louth/client-test -f ./client/Dockerfile.dev ./client

# script:
  # - docker run -e CI=true louth/client-test npm test -- --coverage

after_success:
  - docker build -t louth/multi-nginx ./nginx
  - docker build -t louth/multi-server ./server
  - docker build -t louth/multi-client ./client
  - docker build -t louth/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push louth/multi-nginx
  - docker push louth/multi-server
  - docker push louth/multi-client
  - docker push louth/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: ap-southeast-2
#   app: multi-docker
#   env: MultiDocker-env-1
#   bucket-name: elasticbeanstalk-ap-southeast-2-733387177202
#   bucket-path: multi-docker
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
